import org.yaml.snakeyaml.Yaml

Map manifest = new Yaml().load(readFileFromWorkspace('seed/repos.yaml')) as Map
Map cfg = manifest.config as Map
String seedProject = seedRepoUrl.replaceAll('^.*?://[^/]+/', '')

folder('admin') {
    description('CBD admin jobs. Generated by the seed job - do not edit manually.')
}

pipelineJob('admin/seed') {
    description('Regenerates all Jenkins jobs from repos.yaml in the seed repo. Generated by the seed job (self-managed).')

    parameters {
        stringParam('GIT_URL', seedRepoUrl, 'Seed repo URL containing repos.yaml')
    }

    properties {
        pipelineTriggers {
            triggers {
                gerrit {
                    events {
                        changeMerged()
                    }
                    project('plain:' + seedProject, ['plain:' + cfg.pipelineBranch])
                }
            }
        }
    }

    definition {
        cpsScm {
            scm {
                git {
                    remote {
                        url(cfg.pipelineRepoUrl)
                    }
                    branch("*/${cfg.pipelineBranch}")
                }
            }
            scriptPath('src/Jenkinsfile.seed')
        }
    }
}

pipelineJob('admin/all-services') {
    description('Triggers all service jobs in parallel. Generated by the seed job.')

    parameters {
        stringParam('SERVICE_FOLDER', "${manifest.projects.first().name}/svc", 'Jenkins folder containing the service jobs')
        booleanParam('DEPLOY_TO_PROD', false, 'Deploy master to production')
        booleanParam('DEPLOY_ALL_DEV', false, 'Deploy master to all dev env')
        stringParam('DEPLOY_TO_FRIEND', '', 'Deploy to friends environment')
    }

    definition {
        cpsScm {
            scm {
                git {
                    remote {
                        url(cfg.pipelineRepoUrl)
                    }
                    branch("*/${cfg.pipelineBranch}")
                }
            }
            scriptPath('src/Jenkinsfile.all-services')
        }
    }
}

pipelineJob('admin/update-all') {
    description('Creates Jira sub-tasks and rebuilds all services for a story. Generated by the seed job.')

    parameters {
        stringParam('STORY_NUMBER', '', 'Jira story under which update sub-tasks are created')
    }

    definition {
        cpsScm {
            scm {
                git {
                    remote {
                        url(cfg.pipelineRepoUrl)
                    }
                    branch("*/${cfg.pipelineBranch}")
                }
            }
            scriptPath('src/Jenkinsfile.update')
        }
    }
}
