import org.yaml.snakeyaml.Yaml

Map manifest = new Yaml().load(readFileFromWorkspace('seed/repos.yaml')) as Map
Map cfg = manifest.config as Map

Map jenkinsfileByType = [
        svc    : 'src/Jenkinsfile',
        lib    : 'src/Jenkinsfile.bin',
        docker : 'src/Jenkinsfile.docker',
        scripts: 'src/Jenkinsfile.scripts',
]

manifest.projects.each { Map project ->
    folder(project.name) {
        description("CBD pipeline jobs for project ${project.name}. Generated by the seed job - do not edit manually.")
    }

    project.repos.each { Map repo ->
        String jenkinsfilePath = jenkinsfileByType[repo.type]
        if (!jenkinsfilePath) {
            throw new IllegalArgumentException(
                    "Unknown type '${repo.type}' for repo '${repo.name}' in project '${project.name}'. " +
                            "Allowed: ${jenkinsfileByType.keySet()}")
        }
    }

    project.repos.collect { it.type }.unique().each { String type ->
        folder("${project.name}/${type}") {
            description("CBD ${type} jobs for project ${project.name}. Generated by the seed job - do not edit manually.")
        }
    }

    project.repos.each { Map repo ->
        String jenkinsfilePath = jenkinsfileByType[repo.type]
        String gerritProject = repo.project ?: "${project.name}/${repo.name}"

        pipelineJob("${project.name}/${repo.type}/${repo.name}") {
            description("CBD pipeline for ${gerritProject} (type: ${repo.type}). Generated by the seed job.")

            parameters {
                booleanParam('RUN_SETUP', false, 'Used only when project is being configured')
                stringParam('GIT_URL', "${cfg.gerritSshUrl}/${gerritProject}", 'Git repo URL')
                stringParam('GERRIT_REFSPEC', "refs/heads/${cfg.pipelineBranch}", 'Refspec of change')
                stringParam('GERRIT_BRANCH', cfg.pipelineBranch, 'Branch or commit-id')
                activeChoiceParam('DEPLOY_TO_FRIEND') {
                    description('Select to deploy to friends environment')
                    choiceType('SINGLE_SELECT')
                    groovyScript {
                        script('return [""] + new groovy.json.JsonSlurper().parse(new File("/var/lib/jenkins/accounts.json")).devAccounts.collect{ it.name }')
                        fallbackScript('return [""]')
                    }
                }
                booleanParam('ROLLOUT_TO_ALL', true, 'After merge deploy to all dev environments')
                booleanParam('DEPLOY_TO_PROD', false, 'Deploy master to production')
                booleanParam('DEPLOY_ALL_DEV', false, 'Deploy master to all dev env')
            }

            properties {
                pipelineTriggers {
                    triggers {
                        gerrit {
                            events {
                                patchsetCreated()
                            }
                            project('plain:' + gerritProject, ['plain:' + cfg.pipelineBranch])
                            configure { gerritTrigger ->
                                gerritTrigger / 'triggerOnEvents' << 'com.sonyericsson.hudson.plugins.gerrit.trigger.hudsontrigger.events.PluginCommentAddedEvent' {
                                    verdictCategory('Code-Review')
                                    commentAddedTriggerApprovalValue('+2')
                                }
                            }
                        }
                    }
                }
            }

            definition {
                cpsScm {
                    scm {
                        git {
                            remote {
                                url(cfg.pipelineRepoUrl)
                            }
                            branch("*/${cfg.pipelineBranch}")
                        }
                    }
                    scriptPath(jenkinsfilePath)
                }
            }
        }
    }
}
